create type nyang.mc_item_category as enum ('crop', 'mineral');

create table nyang.mc_market_items (
  symbol          text primary key,
  display_name    text not null,
  category        nyang.mc_item_category not null,
  base_price      integer not null,
  min_price       integer not null,
  max_price       integer not null,
  mc_material     text not null,
  enabled         boolean not null default true
);

create table nyang.mc_market_prices (
  symbol          text primary key references nyang.mc_market_items(symbol),
  current_price   integer not null,
  change_pct      numeric(6,2) not null default 0,
  updated_at      timestamptz not null default now()
);

create table nyang.mc_price_history (
  id              bigint generated by default as identity primary key,
  symbol          text not null references nyang.mc_market_items(symbol),
  price           integer not null,
  recorded_at     timestamptz not null default now()
);
create index on nyang.mc_price_history(symbol, recorded_at desc);

-- Seed: crops
insert into nyang.mc_market_items (symbol, display_name, category, base_price, min_price, max_price, mc_material) values
  ('wheat',       '밀',          'crop',    8,   4,  20, 'WHEAT'),
  ('potato',      '감자',        'crop',    6,   3,  15, 'POTATO'),
  ('carrot',      '당근',        'crop',    7,   3,  18, 'CARROT'),
  ('sugar_cane',  '사탕수수',    'crop',    5,   2,  13, 'SUGAR_CANE'),
  ('pumpkin',     '호박',        'crop',   12,   6,  30, 'PUMPKIN'),
  ('melon_slice', '수박 슬라이스','crop',   4,   2,  10, 'MELON_SLICE'),
  ('beetroot',    '비트루트',    'crop',    9,   4,  22, 'BEETROOT'),
  ('cocoa_beans', '코코아',      'crop',   15,   7,  38, 'COCOA_BEANS');

-- Seed: minerals
insert into nyang.mc_market_items (symbol, display_name, category, base_price, min_price, max_price, mc_material) values
  ('coal',            '석탄',            'mineral',   5,   2,  13, 'COAL'),
  ('iron_ingot',      '철 주괴',         'mineral',  18,   9,  45, 'IRON_INGOT'),
  ('gold_ingot',      '금 주괴',         'mineral',  35,  17,  88, 'GOLD_INGOT'),
  ('copper_ingot',    '구리 주괴',       'mineral',  10,   5,  25, 'COPPER_INGOT'),
  ('lapis_lazuli',    '청금석',          'mineral',  20,  10,  50, 'LAPIS_LAZULI'),
  ('redstone',        '레드스톤',        'mineral',  12,   6,  30, 'REDSTONE'),
  ('diamond',         '다이아몬드',      'mineral', 120,  60, 300, 'DIAMOND'),
  ('emerald',         '에메랄드',        'mineral',  90,  45, 225, 'EMERALD'),
  ('netherite_scrap', '네더라이트 스크랩','mineral', 300, 150, 750, 'NETHERITE_SCRAP');

-- Init prices from base_price
insert into nyang.mc_market_prices (symbol, current_price, change_pct)
select symbol, base_price, 0 from nyang.mc_market_items;
