create table nyang.mc_market_trades (
  id              bigint generated by default as identity primary key,
  minecraft_uuid  text not null references nyang.minecraft_players(minecraft_uuid),
  symbol          text not null,
  qty             integer not null,
  unit_price      integer not null,
  base_price      integer not null,
  freshness_pct   numeric(5,2),
  purity_pct      numeric(5,2),
  fee_amount      integer not null default 0,
  net_points      integer not null,
  side            text not null check (side in ('sell','buy')),
  created_at      timestamptz not null default now()
);
create index on nyang.mc_market_trades(minecraft_uuid, created_at desc);
