create table nyang.mc_quest_templates (
  id              text primary key,
  job_type        nyang.mc_job_type,
  description     text not null,
  target_type     text not null,
  target_material text,
  target_qty      integer not null,
  reward_points   integer not null
);

create table nyang.mc_daily_quests (
  id              bigint generated by default as identity primary key,
  minecraft_uuid  text not null references nyang.minecraft_players(minecraft_uuid),
  quest_id        text not null references nyang.mc_quest_templates(id),
  progress        integer not null default 0,
  completed       boolean not null default false,
  claimed         boolean not null default false,
  quest_date      date not null,
  created_at      timestamptz not null default now(),
  unique(minecraft_uuid, quest_date, quest_id)
);

-- Seed quest templates
insert into nyang.mc_quest_templates (id, job_type, description, target_type, target_material, target_qty, reward_points) values
  ('harvest_wheat_20',  'farmer', '밀 20개 수확',            'harvest', 'WHEAT',      20,  50),
  ('harvest_any_30',     null,    '작물 30개 수확',           'harvest', null,         30,  40),
  ('mine_iron_10',      'miner',  '철광석 10개 채굴',         'mine',    'IRON_ORE',   10,  60),
  ('mine_any_20',        null,    '광물 20개 채굴',           'mine',    null,         20,  45),
  ('sell_crop_50p',      null,    '작물 50P 이상 판매',       'sell',    'crop',        1,  30),
  ('sell_mineral_100p', 'miner',  '광물 100P 이상 판매',      'sell',    'mineral',     1,  80);
