create table nyang.mc_p2p_listings (
  id              bigint generated by default as identity primary key,
  seller_uuid     text not null references nyang.minecraft_players(minecraft_uuid),
  symbol          text not null references nyang.mc_market_items(symbol),
  qty             integer not null,
  price_per_unit  integer not null,
  status          text not null default 'open' check (status in ('open','sold','cancelled')),
  buyer_uuid      text references nyang.minecraft_players(minecraft_uuid),
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index on nyang.mc_p2p_listings(status, symbol);
